spring:
  datasource:
    url: jdbc:mysql://172.22.0.2:3306/bank_db
    username: root
    password: rootpassword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop
    generate-ddl: true
  data:
    redis:
      host: 172.23.0.2
      port: 6379
rsa:
  private-key: classpath:certs/private-keyy.pem
  public-key: classpath:certs/public-key.pem

server:
    port: 8082
    max-http-header-size: 2000

redis:
  pub_sub:
    topic: auction-events